var hooks = new EventManager();
var actionHistory = {};
var globals = {};
var INIT = globals.INIT = 'init';
var REGISTER = globals.REGISTER = 'initRegister';
var READY = globals.READY = 'initReady';
var HASH_STATE_CHANGE = globals.HASH_STATE_CHANGE = 'hashStateChange';
var SET_HASH_STATE = globals.SET_HASH_STATE = 'setHashState';
var LAYOUT = globals.LAYOUT = 'layout';
var LAYOUTEND = globals.LAYOUTEND = 'layoutEnd';
var SCROLLSTART = globals.SCROLLSTART = 'scrollStart';
var SCROLL = globals.SCROLL = 'scroll';
var SCROLLEND = globals.SCROLLEND = 'scrollEnd';
var USER_FIRST_INTERACTION = globals.USER_FIRST_INTERACTION = 'userFirstInteraction';
var GFORM_CONFIRM = globals.GFORM_CONFIRM = 'gformConfirmation';
var GA_EVENT = globals.GA_EVENT = 'gaEvent';
var GTM_INTERACTION = globals.GTM_INTERACTION = 'dataLayerInteraction';
var GTM_STATE = globals.GTM_STATE = 'dataLayerState';
var TRANSITION_END_EVENT = globals.TRANSITION_END_EVENT = "webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend";
var isiOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
var _ = window.lodash = window._.noConflict();
